### ISSUE TITLE
Maquetar hero section

### ISSUE THREAD

**Issue by lemartinezm** [Open-Bootcamp/dev-blog#4]
El usuario observa:
   - [x] Nombre del creador del blog y pequeña descripción
   - [x] Imagen de fondo
  
   Tener en cuenta:
   - [x] Diseño responsive

**Comment by 3v3AH** [comment]
Hola chicos, tengo una idea en que pongamos los 3 nombres de nosotros como los creadores del blog, una descripcion de nosotros y la imagen. Quizá sea algo descabellado. Quedo atenta a sus comentarios.

**Comment by webdevelopersbierzo** [comment]
Por mi bien, aunque creo mejor ceñirse primero en las tareas y luego ampliamos pienso yo

**Comment by lemartinezm** [comment]
Correcto, primero hay que completar la maquetación y luego se puede cambiar valores como el creador del blog, etc
